### ISSUE TITLE
where  to get pickled /binary object of this dataset

### ISSUE THREAD

**Issue by assadRasheed** [uchidalab/book-dataset#3]
i am trying to run this dataset but it is quite time consuming and heave.is there  form like ciphar10 binary or pickled dataset of above mention datasets

**Comment by biwana** [comment]
Sorry, we don't provide a binary of this dataset because 
1. It would be too large. Cifar10 uses 32x32 images which is tiny. 
2. Hosting the images might go beyond what fair use allows.
