### ISSUE TITLE
Connectivity issue causes script to crash

### ISSUE THREAD

**Issue by kingcobra2468** [uchidalab/book-dataset#8]
If a `ConnectionResetError` exception is thrown while an image is being download, the script will crash. There should be some sort of auto-recovery mechanism that attempts to recover the script instead of the existing logic which results in lost progress (since the script will have to be re-run again if an crash occurs).

**Comment by biwana** [comment]
The script wasn't designed by us. It was a pull request. 

However, a simple check to see if the file exists on your computer (= you already downloaded it) would fix this problem. 
something as easy as:
if not os.file.exists(output_filepath):
   // do whatever
